services:
  bluecore-store:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: bluecore_admin
      POSTGRES_PASSWORD: bluecore_admin
      POSTGRES_DB: bluecore
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bluecore_admin"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  bc_api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      bluecore-store:
        condition: service_healthy
    ports:
      - "8100:8100"
    volumes:
      - .:/app
    environment:
      UV_CACHE_DIR: /tmp/uv-cache
      DATABASE_URL: postgresql+psycopg2://bluecore_admin:bluecore_admin@bluecore-store:5432/bluecore
      DEVELOPER_MODE: "true"
    command: ["uv", "run", "fastapi", "run", "src/bluecore/app/main.py", "--port", "8100", "--root-path", "/api"]

volumes:
  postgres-db-volume:
